
Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Vette.GoogleTagManager:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Vette.GoogleTagManager: true
